In [1]:
import os
import glob
import pandas as pd

In [2]:
folder_path = 'C:/Users/johfr/Dropbox/Skule/Data science/Bachelor/Dataset/DDoS/'

In [3]:
#Data preperation
df = pd.read_csv(folder_path + 'combined_ddos.csv')

In [4]:
df.head()

,Src Port,Dst Port,Protocol,Flow Duration,Total Fwd Packet,Total Bwd packets,Total Length of Fwd Packet,Total Length of Bwd Packet,Fwd Packet Length Max,Fwd Packet Length Min,...,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label,Flow ID,Src IP,Dst IP,Timestamp
0,48548,55442,6,109779099,2,0,2920.0,0.0,1460.0,1460.0,...,0.0,109779099.0,0.0,109779099.0,109779099.0,0,NaN,NaN,NaN,NaN
1,80,7433,6,18224,1,1,0.0,1460.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,NaN,NaN,NaN,NaN
2,24717,8080,6,55131335,2,0,2920.0,0.0,1460.0,1460.0,...,0.0,55131335.0,0.0,55131335.0,55131335.0,0,NaN,NaN,NaN,NaN
3,80,65224,6,43200,1,1,0.0,1460.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,NaN,NaN,NaN,NaN
4,53,17257,6,58985,1,1,0.0,1460.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,NaN,NaN,NaN,NaN

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 391893 entries, 0 to 391892
Data columns (total 84 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Src Port                    391893 non-null  int64
 1   Dst Port                    391893 non-null  int64
 2   Protocol                    391893 non-null  int64
 3   Flow Duration               391893 non-null  int64
 4   Total Fwd Packet            391893 non-null  int64
 5   Total Bwd packets           391893 non-null  int64
 6   Total Length of Fwd Packet  391893 non-null  float64
 7   Total Length of Bwd Packet  391893 non-null  float64
 8   Fwd Packet Length Max       391893 non-null  float64
 9   Fwd Packet Length Min       391893 non-null  float64
 10  Fwd Packet Length Mean      391893 non-null  float64
 11  Fwd Packet Length Std       391893 non-null  float64
 12  Bwd Packet Length Max       391893 non-null  float64
 13  Bwd Packet Length Min       391893 non-null  float64
 14  Bwd Packet Length Mean      391893 non-null  float64
 15  Bwd Packet Length Std       391893 non-null  float64
 16  Flow Bytes/s                391523 non-null  float64
 17  Flow Packets/s              391893 non-null  float64
 18  Flow IAT Mean               391893 non-null  float64
 19  Flow IAT Std                391893 non-null  float64
 20  Flow IAT Max                391893 non-null  float64
 21  Flow IAT Min                391893 non-null  float64
 22  Fwd IAT Total               391893 non-null  float64
 23  Fwd IAT Mean                391893 non-null  float64
 24  Fwd IAT Std                 391893 non-null  float64
 25  Fwd IAT Max                 391893 non-null  float64
 26  Fwd IAT Min                 391893 non-null  float64
 27  Bwd IAT Total               391893 non-null  float64
 28  Bwd IAT Mean                391893 non-null  float64
 29  Bwd IAT Std                 391893 non-null  float64
 30  Bwd IAT Max                 391893 non-null  float64
 31  Bwd IAT Min                 391893 non-null  float64
 32  Fwd PSH Flags               391893 non-null  int64
 33  Bwd PSH Flags               391893 non-null  int64
 34  Fwd URG Flags               391893 non-null  int64
 35  Bwd URG Flags               391893 non-null  int64
 36  Fwd Header Length           391893 non-null  int64
 37  Bwd Header Length           391893 non-null  int64
 38  Fwd Packets/s               391893 non-null  float64
 39  Bwd Packets/s               391893 non-null  float64
 40  Packet Length Min           391893 non-null  float64
 41  Packet Length Max           391893 non-null  float64
 42  Packet Length Mean          391893 non-null  float64
 43  Packet Length Std           391893 non-null  float64
 44  Packet Length Variance      391893 non-null  float64
 45  FIN Flag Count              391893 non-null  int64
 46  SYN Flag Count              391893 non-null  int64
 47  RST Flag Count              391893 non-null  int64
 48  PSH Flag Count              391893 non-null  int64
 49  ACK Flag Count              391893 non-null  int64
 50  URG Flag Count              391893 non-null  int64
 51  CWR Flag Count              391893 non-null  int64
 52  ECE Flag Count              391893 non-null  int64
 53  Down/Up Ratio               391893 non-null  float64
 54  Average Packet Size         391893 non-null  float64
 55  Fwd Segment Size Avg        391893 non-null  float64
 56  Bwd Segment Size Avg        391893 non-null  float64
 57  Fwd Bytes/Bulk Avg          391893 non-null  int64
 58  Fwd Packet/Bulk Avg         391893 non-null  int64
 59  Fwd Bulk Rate Avg           391893 non-null  int64
 60  Bwd Bytes/Bulk Avg          391893 non-null  int64
 61  Bwd Packet/Bulk Avg         391893 non-null  int64
 62  Bwd Bulk Rate Avg           391893 non-null  int64
 63  Subflow Fwd Packets         391893 non-null  int64
 64  Subflow Fwd Bytes           391893 non-null  int64
 65  Subflow Bwd Packets         391893 non-null  int64
 66  Subflow Bwd Bytes           391893 non-null  int64
 67  FWD Init Win Bytes          391893 non-null  int64
 68  Bwd Init Win Bytes          391893 non-null  int64
 69  Fwd Act Data Pkts           391893 non-null  int64
 70  Fwd Seg Size Min            391893 non-null  int64
 71  Active Mean                 391893 non-null  float64
 72  Active Std                  391893 non-null  float64
 73  Active Max                  391893 non-null  float64
 74  Active Min                  391893 non-null  float64
 75  Idle Mean                   391893 non-null  float64
 76  Idle Std                    391893 non-null  float64
 77  Idle Max                    391893 non-null  float64
 78  Idle Min                    391893 non-null  float64
 79  Label                       391893 non-null  str
 80  Flow ID                     385468 non-null  str
 81  Src IP                      385468 non-null  str
 82  Dst IP                      385468 non-null  str
 83  Timestamp                   385468 non-null  str
dtypes: float64(45), int64(34), str(5)
memory usage: 251.2 MB

In [6]:
df.drop(columns=['Flow ID', 'Src IP', 'Dst IP', 'Timestamp'], inplace=True)

In [7]:
df['Label'] = 1

In [8]:
df.head()

,Src Port,Dst Port,Protocol,Flow Duration,Total Fwd Packet,Total Bwd packets,Total Length of Fwd Packet,Total Length of Bwd Packet,Fwd Packet Length Max,Fwd Packet Length Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,48548,55442,6,109779099,2,0,2920.0,0.0,1460.0,1460.0,...,20,0.0,0.0,0.0,0.0,109779099.0,0.0,109779099.0,109779099.0,1
1,80,7433,6,18224,1,1,0.0,1460.0,0.0,0.0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2,24717,8080,6,55131335,2,0,2920.0,0.0,1460.0,1460.0,...,20,0.0,0.0,0.0,0.0,55131335.0,0.0,55131335.0,55131335.0,1
3,80,65224,6,43200,1,1,0.0,1460.0,0.0,0.0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
4,53,17257,6,58985,1,1,0.0,1460.0,0.0,0.0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

In [9]:
output_file = os.path.join(folder_path, 'combined_ddos.csv')
df.to_csv(output_file, index=False)