In [1]:
import os
import glob
import pandas as pd

In [2]:
folder_path = 'C:/Users/johfr/Dropbox/Skule/Data science/Bachelor/Dataset/DoS/'

In [3]:
#Data preperation
df = pd.read_csv(folder_path + 'combined_dos.csv')

In [4]:
df.head()

,Flow ID,Src IP,Src Port,Dst IP,Dst Port,Protocol,Timestamp,Flow Duration,Total Fwd Packet,Total Bwd packets,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,192.168.137.66-192.168.137.64-52196-80-6,192.168.137.66,52196,192.168.137.64,80,6,08/08/2022 05:04:02 PM,2494,1,1,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NeedManualLabel
1,192.168.137.66-192.168.137.211-54214-8080-6,192.168.137.66,54214,192.168.137.211,8080,6,08/08/2022 04:31:11 PM,52850,1,1,...,40,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NeedManualLabel
2,192.168.137.66-192.168.137.211-33056-8080-6,192.168.137.66,33056,192.168.137.211,8080,6,08/08/2022 04:32:07 PM,99319,1,1,...,40,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NeedManualLabel
3,192.168.137.66-192.168.137.211-56896-8080-6,192.168.137.66,56896,192.168.137.211,8080,6,08/08/2022 04:40:39 PM,100282,1,1,...,40,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NeedManualLabel
4,192.168.137.1-192.168.137.158-53-58791-17,192.168.137.1,53,192.168.137.158,58791,17,08/08/2022 03:39:13 PM,157192,1,1,...,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NeedManualLabel

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 331955 entries, 0 to 331954
Data columns (total 84 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Flow ID                     331955 non-null  str
 1   Src IP                      331955 non-null  str
 2   Src Port                    331955 non-null  int64
 3   Dst IP                      331955 non-null  str
 4   Dst Port                    331955 non-null  int64
 5   Protocol                    331955 non-null  int64
 6   Timestamp                   331955 non-null  str
 7   Flow Duration               331955 non-null  int64
 8   Total Fwd Packet            331955 non-null  int64
 9   Total Bwd packets           331955 non-null  int64
 10  Total Length of Fwd Packet  331955 non-null  float64
 11  Total Length of Bwd Packet  331955 non-null  float64
 12  Fwd Packet Length Max       331955 non-null  float64
 13  Fwd Packet Length Min       331955 non-null  float64
 14  Fwd Packet Length Mean      331955 non-null  float64
 15  Fwd Packet Length Std       331955 non-null  float64
 16  Bwd Packet Length Max       331955 non-null  float64
 17  Bwd Packet Length Min       331955 non-null  float64
 18  Bwd Packet Length Mean      331955 non-null  float64
 19  Bwd Packet Length Std       331955 non-null  float64
 20  Flow Bytes/s                330100 non-null  float64
 21  Flow Packets/s              331955 non-null  float64
 22  Flow IAT Mean               331955 non-null  float64
 23  Flow IAT Std                331955 non-null  float64
 24  Flow IAT Max                331955 non-null  float64
 25  Flow IAT Min                331955 non-null  float64
 26  Fwd IAT Total               331955 non-null  float64
 27  Fwd IAT Mean                331955 non-null  float64
 28  Fwd IAT Std                 331955 non-null  float64
 29  Fwd IAT Max                 331955 non-null  float64
 30  Fwd IAT Min                 331955 non-null  float64
 31  Bwd IAT Total               331955 non-null  float64
 32  Bwd IAT Mean                331955 non-null  float64
 33  Bwd IAT Std                 331955 non-null  float64
 34  Bwd IAT Max                 331955 non-null  float64
 35  Bwd IAT Min                 331955 non-null  float64
 36  Fwd PSH Flags               331955 non-null  int64
 37  Bwd PSH Flags               331955 non-null  int64
 38  Fwd URG Flags               331955 non-null  int64
 39  Bwd URG Flags               331955 non-null  int64
 40  Fwd Header Length           331955 non-null  int64
 41  Bwd Header Length           331955 non-null  int64
 42  Fwd Packets/s               331955 non-null  float64
 43  Bwd Packets/s               331955 non-null  float64
 44  Packet Length Min           331955 non-null  float64
 45  Packet Length Max           331955 non-null  float64
 46  Packet Length Mean          331955 non-null  float64
 47  Packet Length Std           331955 non-null  float64
 48  Packet Length Variance      331955 non-null  float64
 49  FIN Flag Count              331955 non-null  int64
 50  SYN Flag Count              331955 non-null  int64
 51  RST Flag Count              331955 non-null  int64
 52  PSH Flag Count              331955 non-null  int64
 53  ACK Flag Count              331955 non-null  int64
 54  URG Flag Count              331955 non-null  int64
 55  CWR Flag Count              331955 non-null  int64
 56  ECE Flag Count              331955 non-null  int64
 57  Down/Up Ratio               331955 non-null  float64
 58  Average Packet Size         331955 non-null  float64
 59  Fwd Segment Size Avg        331955 non-null  float64
 60  Bwd Segment Size Avg        331955 non-null  float64
 61  Fwd Bytes/Bulk Avg          331955 non-null  int64
 62  Fwd Packet/Bulk Avg         331955 non-null  int64
 63  Fwd Bulk Rate Avg           331955 non-null  int64
 64  Bwd Bytes/Bulk Avg          331955 non-null  int64
 65  Bwd Packet/Bulk Avg         331955 non-null  int64
 66  Bwd Bulk Rate Avg           331955 non-null  int64
 67  Subflow Fwd Packets         331955 non-null  int64
 68  Subflow Fwd Bytes           331955 non-null  int64
 69  Subflow Bwd Packets         331955 non-null  int64
 70  Subflow Bwd Bytes           331955 non-null  int64
 71  FWD Init Win Bytes          331955 non-null  int64
 72  Bwd Init Win Bytes          331955 non-null  int64
 73  Fwd Act Data Pkts           331955 non-null  int64
 74  Fwd Seg Size Min            331955 non-null  int64
 75  Active Mean                 331955 non-null  float64
 76  Active Std                  331955 non-null  float64
 77  Active Max                  331955 non-null  float64
 78  Active Min                  331955 non-null  float64
 79  Idle Mean                   331955 non-null  float64
 80  Idle Std                    331955 non-null  float64
 81  Idle Max                    331955 non-null  float64
 82  Idle Min                    331955 non-null  float64
 83  Label                       331955 non-null  str
dtypes: float64(45), int64(34), str(5)
memory usage: 212.7 MB

In [6]:
df.drop(columns=['Flow ID', 'Src IP', 'Dst IP', 'Timestamp'], inplace=True)

In [7]:
df['Label'] = 1

In [8]:
df.head()

,Src Port,Dst Port,Protocol,Flow Duration,Total Fwd Packet,Total Bwd packets,Total Length of Fwd Packet,Total Length of Bwd Packet,Fwd Packet Length Max,Fwd Packet Length Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,52196,80,6,2494,1,1,0.0,536.0,0.0,0.0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1,54214,8080,6,52850,1,1,0.0,0.0,0.0,0.0,...,40,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2,33056,8080,6,99319,1,1,0.0,0.0,0.0,0.0,...,40,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
3,56896,8080,6,100282,1,1,0.0,0.0,0.0,0.0,...,40,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
4,53,58791,17,157192,1,1,44.0,28.0,44.0,44.0,...,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

In [9]:
output_file = os.path.join(folder_path, 'combined_dos.csv')
df.to_csv(output_file, index=False)