In [1]:
import os
import glob
import pandas as pd

In [2]:
folder_path = 'C:\\Users\\johfr\\Dropbox\\Skule\\Data science\\Bachelor\\Dataset\\Recon\\'

In [4]:
#Data preperation
df = pd.read_csv(folder_path + 'VulnerabilityScan.pcap_Flow.csv')

In [5]:
df.head()

,Flow ID,Src IP,Src Port,Dst IP,Dst Port,Protocol,Timestamp,Flow Duration,Total Fwd Packet,Total Bwd packets,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,192.168.137.41-157.249.81.141-51523-80-6,192.168.137.41,51523,157.249.81.141,80,6,03/10/2022 11:02:01 AM,287014,5,4,...,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NeedManualLabel
1,192.168.137.41-157.249.81.141-49873-443-6,192.168.137.41,49873,157.249.81.141,443,6,03/10/2022 11:02:02 AM,288538,5,4,...,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NeedManualLabel
2,192.168.137.41-157.249.81.141-51526-80-6,192.168.137.41,51526,157.249.81.141,80,6,03/10/2022 11:02:03 AM,289027,5,4,...,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NeedManualLabel
3,192.168.137.41-157.249.81.141-49876-443-6,192.168.137.41,49876,157.249.81.141,443,6,03/10/2022 11:02:03 AM,287662,5,4,...,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NeedManualLabel
4,192.168.137.41-157.249.81.141-51529-80-6,192.168.137.41,51529,157.249.81.141,80,6,03/10/2022 11:02:05 AM,287707,5,4,...,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NeedManualLabel

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 442158 entries, 0 to 442157
Data columns (total 84 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Flow ID                     442158 non-null  str
 1   Src IP                      442158 non-null  str
 2   Src Port                    442158 non-null  int64
 3   Dst IP                      442158 non-null  str
 4   Dst Port                    442158 non-null  int64
 5   Protocol                    442158 non-null  int64
 6   Timestamp                   442158 non-null  str
 7   Flow Duration               442158 non-null  int64
 8   Total Fwd Packet            442158 non-null  int64
 9   Total Bwd packets           442158 non-null  int64
 10  Total Length of Fwd Packet  442158 non-null  float64
 11  Total Length of Bwd Packet  442158 non-null  float64
 12  Fwd Packet Length Max       442158 non-null  float64
 13  Fwd Packet Length Min       442158 non-null  float64
 14  Fwd Packet Length Mean      442158 non-null  float64
 15  Fwd Packet Length Std       442158 non-null  float64
 16  Bwd Packet Length Max       442158 non-null  float64
 17  Bwd Packet Length Min       442158 non-null  float64
 18  Bwd Packet Length Mean      442158 non-null  float64
 19  Bwd Packet Length Std       442158 non-null  float64
 20  Flow Bytes/s                441637 non-null  float64
 21  Flow Packets/s              442158 non-null  float64
 22  Flow IAT Mean               442158 non-null  float64
 23  Flow IAT Std                442158 non-null  float64
 24  Flow IAT Max                442158 non-null  float64
 25  Flow IAT Min                442158 non-null  float64
 26  Fwd IAT Total               442158 non-null  float64
 27  Fwd IAT Mean                442158 non-null  float64
 28  Fwd IAT Std                 442158 non-null  float64
 29  Fwd IAT Max                 442158 non-null  float64
 30  Fwd IAT Min                 442158 non-null  float64
 31  Bwd IAT Total               442158 non-null  float64
 32  Bwd IAT Mean                442158 non-null  float64
 33  Bwd IAT Std                 442158 non-null  float64
 34  Bwd IAT Max                 442158 non-null  float64
 35  Bwd IAT Min                 442158 non-null  float64
 36  Fwd PSH Flags               442158 non-null  int64
 37  Bwd PSH Flags               442158 non-null  int64
 38  Fwd URG Flags               442158 non-null  int64
 39  Bwd URG Flags               442158 non-null  int64
 40  Fwd Header Length           442158 non-null  int64
 41  Bwd Header Length           442158 non-null  int64
 42  Fwd Packets/s               442158 non-null  float64
 43  Bwd Packets/s               442158 non-null  float64
 44  Packet Length Min           442158 non-null  float64
 45  Packet Length Max           442158 non-null  float64
 46  Packet Length Mean          442158 non-null  float64
 47  Packet Length Std           442158 non-null  float64
 48  Packet Length Variance      442158 non-null  float64
 49  FIN Flag Count              442158 non-null  int64
 50  SYN Flag Count              442158 non-null  int64
 51  RST Flag Count              442158 non-null  int64
 52  PSH Flag Count              442158 non-null  int64
 53  ACK Flag Count              442158 non-null  int64
 54  URG Flag Count              442158 non-null  int64
 55  CWR Flag Count              442158 non-null  int64
 56  ECE Flag Count              442158 non-null  int64
 57  Down/Up Ratio               442158 non-null  float64
 58  Average Packet Size         442158 non-null  float64
 59  Fwd Segment Size Avg        442158 non-null  float64
 60  Bwd Segment Size Avg        442158 non-null  float64
 61  Fwd Bytes/Bulk Avg          442158 non-null  int64
 62  Fwd Packet/Bulk Avg         442158 non-null  int64
 63  Fwd Bulk Rate Avg           442158 non-null  int64
 64  Bwd Bytes/Bulk Avg          442158 non-null  int64
 65  Bwd Packet/Bulk Avg         442158 non-null  int64
 66  Bwd Bulk Rate Avg           442158 non-null  int64
 67  Subflow Fwd Packets         442158 non-null  int64
 68  Subflow Fwd Bytes           442158 non-null  int64
 69  Subflow Bwd Packets         442158 non-null  int64
 70  Subflow Bwd Bytes           442158 non-null  int64
 71  FWD Init Win Bytes          442158 non-null  int64
 72  Bwd Init Win Bytes          442158 non-null  int64
 73  Fwd Act Data Pkts           442158 non-null  int64
 74  Fwd Seg Size Min            442158 non-null  int64
 75  Active Mean                 442158 non-null  float64
 76  Active Std                  442158 non-null  float64
 77  Active Max                  442158 non-null  float64
 78  Active Min                  442158 non-null  float64
 79  Idle Mean                   442158 non-null  float64
 80  Idle Std                    442158 non-null  float64
 81  Idle Max                    442158 non-null  float64
 82  Idle Min                    442158 non-null  float64
 83  Label                       442158 non-null  str
dtypes: float64(45), int64(34), str(5)
memory usage: 283.4 MB

In [7]:
df.drop(columns=['Flow ID', 'Src IP', 'Dst IP', 'Timestamp'], inplace=True)

In [8]:
df['Label'] = 1

In [9]:
df.head()

,Src Port,Dst Port,Protocol,Flow Duration,Total Fwd Packet,Total Bwd packets,Total Length of Fwd Packet,Total Length of Bwd Packet,Fwd Packet Length Max,Fwd Packet Length Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,51523,80,6,287014,5,4,196.0,375.0,196.0,0.0,...,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1,49873,443,6,288538,5,4,251.0,7.0,251.0,0.0,...,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2,51526,80,6,289027,5,4,196.0,375.0,196.0,0.0,...,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
3,49876,443,6,287662,5,4,251.0,7.0,251.0,0.0,...,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
4,51529,80,6,287707,5,4,196.0,375.0,196.0,0.0,...,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

In [10]:
output_file = os.path.join(folder_path, 'combined_recon.csv')
df.to_csv(output_file, index=False)