In [1]:
import os
import glob
import pandas as pd

In [2]:
folder_path = 'C:\\Users\\johfr\\Dropbox\\Skule\\Data science\\Bachelor\\Dataset\\Spoofing\\'

In [3]:
#Data preperation
df = pd.read_csv(folder_path + 'combined_spoofing.csv')

In [4]:
df.head()

,Src Port,Dst Port,Protocol,Flow Duration,Total Fwd Packet,Total Bwd packets,Total Length of Fwd Packet,Total Length of Bwd Packet,Fwd Packet Length Max,Fwd Packet Length Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,32802,443,6,536529,14,13,492.0,4886.0,246.0,0.0,...,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,36702,443,6,1237947,18,17,984.0,6481.0,246.0,0.0,...,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,57751,80,6,82710,1,1,0.0,0.0,0.0,0.0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,43728,443,6,257515,9,8,1173.0,932.0,574.0,0.0,...,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,43856,80,6,450781,6,4,260.0,1391.0,260.0,0.0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 157238 entries, 0 to 157237
Data columns (total 80 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Src Port                    157238 non-null  int64
 1   Dst Port                    157238 non-null  int64
 2   Protocol                    157238 non-null  int64
 3   Flow Duration               157238 non-null  int64
 4   Total Fwd Packet            157238 non-null  int64
 5   Total Bwd packets           157238 non-null  int64
 6   Total Length of Fwd Packet  157238 non-null  float64
 7   Total Length of Bwd Packet  157238 non-null  float64
 8   Fwd Packet Length Max       157238 non-null  float64
 9   Fwd Packet Length Min       157238 non-null  float64
 10  Fwd Packet Length Mean      157238 non-null  float64
 11  Fwd Packet Length Std       157238 non-null  float64
 12  Bwd Packet Length Max       157238 non-null  float64
 13  Bwd Packet Length Min       157238 non-null  float64
 14  Bwd Packet Length Mean      157238 non-null  float64
 15  Bwd Packet Length Std       157238 non-null  float64
 16  Flow Bytes/s                157162 non-null  float64
 17  Flow Packets/s              157238 non-null  float64
 18  Flow IAT Mean               157238 non-null  float64
 19  Flow IAT Std                157238 non-null  float64
 20  Flow IAT Max                157238 non-null  float64
 21  Flow IAT Min                157238 non-null  float64
 22  Fwd IAT Total               157238 non-null  float64
 23  Fwd IAT Mean                157238 non-null  float64
 24  Fwd IAT Std                 157238 non-null  float64
 25  Fwd IAT Max                 157238 non-null  float64
 26  Fwd IAT Min                 157238 non-null  float64
 27  Bwd IAT Total               157238 non-null  float64
 28  Bwd IAT Mean                157238 non-null  float64
 29  Bwd IAT Std                 157238 non-null  float64
 30  Bwd IAT Max                 157238 non-null  float64
 31  Bwd IAT Min                 157238 non-null  float64
 32  Fwd PSH Flags               157238 non-null  int64
 33  Bwd PSH Flags               157238 non-null  int64
 34  Fwd URG Flags               157238 non-null  int64
 35  Bwd URG Flags               157238 non-null  int64
 36  Fwd Header Length           157238 non-null  int64
 37  Bwd Header Length           157238 non-null  int64
 38  Fwd Packets/s               157238 non-null  float64
 39  Bwd Packets/s               157238 non-null  float64
 40  Packet Length Min           157238 non-null  float64
 41  Packet Length Max           157238 non-null  float64
 42  Packet Length Mean          157238 non-null  float64
 43  Packet Length Std           157238 non-null  float64
 44  Packet Length Variance      157238 non-null  float64
 45  FIN Flag Count              157238 non-null  int64
 46  SYN Flag Count              157238 non-null  int64
 47  RST Flag Count              157238 non-null  int64
 48  PSH Flag Count              157238 non-null  int64
 49  ACK Flag Count              157238 non-null  int64
 50  URG Flag Count              157238 non-null  int64
 51  CWR Flag Count              157238 non-null  int64
 52  ECE Flag Count              157238 non-null  int64
 53  Down/Up Ratio               157238 non-null  float64
 54  Average Packet Size         157238 non-null  float64
 55  Fwd Segment Size Avg        157238 non-null  float64
 56  Bwd Segment Size Avg        157238 non-null  float64
 57  Fwd Bytes/Bulk Avg          157238 non-null  int64
 58  Fwd Packet/Bulk Avg         157238 non-null  int64
 59  Fwd Bulk Rate Avg           157238 non-null  int64
 60  Bwd Bytes/Bulk Avg          157238 non-null  int64
 61  Bwd Packet/Bulk Avg         157238 non-null  int64
 62  Bwd Bulk Rate Avg           157238 non-null  int64
 63  Subflow Fwd Packets         157238 non-null  int64
 64  Subflow Fwd Bytes           157238 non-null  int64
 65  Subflow Bwd Packets         157238 non-null  int64
 66  Subflow Bwd Bytes           157238 non-null  int64
 67  FWD Init Win Bytes          157238 non-null  int64
 68  Bwd Init Win Bytes          157238 non-null  int64
 69  Fwd Act Data Pkts           157238 non-null  int64
 70  Fwd Seg Size Min            157238 non-null  int64
 71  Active Mean                 157238 non-null  float64
 72  Active Std                  157238 non-null  float64
 73  Active Max                  157238 non-null  float64
 74  Active Min                  157238 non-null  float64
 75  Idle Mean                   157238 non-null  float64
 76  Idle Std                    157238 non-null  float64
 77  Idle Max                    157238 non-null  float64
 78  Idle Min                    157238 non-null  float64
 79  Label                       157238 non-null  int64
dtypes: float64(45), int64(35)
memory usage: 96.0 MB

In [6]:
df.drop(columns=['Flow ID', 'Src IP', 'Dst IP', 'Timestamp'], inplace=True)

KeyError: "['Flow ID', 'Src IP', 'Dst IP', 'Timestamp'] not found in axis"

In [7]:
df['Label'] = 1

In [8]:
df

,Src Port,Dst Port,Protocol,Flow Duration,Total Fwd Packet,Total Bwd packets,Total Length of Fwd Packet,Total Length of Bwd Packet,Fwd Packet Length Max,Fwd Packet Length Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,32802,443,6,536529,14,13,492.0,4886.0,246.0,0.0,...,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1,36702,443,6,1237947,18,17,984.0,6481.0,246.0,0.0,...,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2,57751,80,6,82710,1,1,0.0,0.0,0.0,0.0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
3,43728,443,6,257515,9,8,1173.0,932.0,574.0,0.0,...,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
4,43856,80,6,450781,6,4,260.0,1391.0,260.0,0.0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157233,53,40062,17,15966,1,1,73.0,41.0,73.0,73.0,...,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
157234,29741,32100,17,119825,1,1,4.0,20.0,4.0,4.0,...,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
157235,38643,5353,17,18,6,0,847.0,0.0,212.0,46.0,...,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
157236,55944,53,17,2892,1,1,41.0,315.0,41.0,41.0,...,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
157237,50383,53,17,9819,1,1,38.0,54.0,38.0,38.0,...,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

In [9]:
output_file = os.path.join(folder_path, 'combined_spoofing.csv')
df.to_csv(output_file, index=False)